ALTER TABLE messages
ADD COLUMN reply_to_id INT NULL,
ADD COLUMN is_forwarded BOOLEAN DEFAULT FALSE,
ADD COLUMN is_deleted BOOLEAN DEFAULT FALSE,
ADD COLUMN reactions JSON,
ADD CONSTRAINT fk_reply_to FOREIGN KEY (reply_to_id) REFERENCES messages(id) ON DELETE SET NULL;
